// Code generated by ogen, DO NOT EDIT.

package api

// InfoGetBadRequest is response for InfoGet operation.
type InfoGetBadRequest struct{}

func (*InfoGetBadRequest) infoGetRes() {}

// InfoGetInternalServerError is response for InfoGet operation.
type InfoGetInternalServerError struct{}

func (*InfoGetInternalServerError) infoGetRes() {}

// Ref: #/components/schemas/SongDetail
type SongDetail struct {
	ReleaseDate string `json:"releaseDate"`
	Text        string `json:"text"`
	Link        string `json:"link"`
}

// GetReleaseDate returns the value of ReleaseDate.
func (s *SongDetail) GetReleaseDate() string {
	return s.ReleaseDate
}

// GetText returns the value of Text.
func (s *SongDetail) GetText() string {
	return s.Text
}

// GetLink returns the value of Link.
func (s *SongDetail) GetLink() string {
	return s.Link
}

// SetReleaseDate sets the value of ReleaseDate.
func (s *SongDetail) SetReleaseDate(val string) {
	s.ReleaseDate = val
}

// SetText sets the value of Text.
func (s *SongDetail) SetText(val string) {
	s.Text = val
}

// SetLink sets the value of Link.
func (s *SongDetail) SetLink(val string) {
	s.Link = val
}

func (*SongDetail) infoGetRes() {}
